export const metadata = {  
    title: " |LMS | Karan's MERN LMS | Engaging Online Learning | LMS for Courses & Collaboration|MERN Stack LMS | Courses, Quizzes, & Discussions|LMS Platform | Create & Collaborate on Online Courses ",  
    description: "Discover learning-bac.vercel.app, a robust Learning Management System (LMS) developed by Karan Kumar. This platform empowers educators and learners to create, manage, and engage with online courses effectively. Featuring tools for course creation, lesson management, discussion forums, assignments, quizzes, and collaborative learning, our MERN Stack-powered LMS provides a seamless and interactive educational experience. Explore our platform for online learning, e-learning, and tech education. Enhance student engagement and utilize instructor tools for efficient course delivery. Learn more about our comprehensive LMS solutions",  
    keywords: [
      "LMS",
      "Article",
      "Documentation",
      "LMS Karan",
      "Learning Management System",
      "Course Creation",
      "Lesson Management",
      "Discussion Forums",
      "Assignments Management",
      "Quizzes",
      "Collaboration Tools",
      "Educational Content",
      "Online Learning",
      "E-Learning",
      "Student Engagement",
      "Instructor Tools",
      "MERN Stack",
      "Next.js",
      "JavaScript",
      "Tech Education",
    ],  
    openGraph: {
      title: "LMS | Create Courses, Collaborate & Manage Learning",
      description: "An advanced LMS platform for course creation, discussions, assignments, collaboration, and interactive learning.",
      url: "https://learning-bac.vercel.app/",
      type: "website",
      images: [
        {
          url: "https://learning-bac.vercel.app/karankumar.jpg",
          width: 1200,
          height: 630,
          alt: "LMS Platform - Courses, Collaboration & Learning",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "LMS | Create Courses, Collaborate & Manage Learning",
      description: "A Next.js-powered LMS platform for course creation, discussions, assignments, and collaboration in online learning.",
      images: ["https://learning-bac.vercel.app/karankumar.jpg"],
    },
  };
  